- name: Verify if a user exists and can be impersonated using SSH
  hosts: "10.112.0.11"
  gather_facts: false
  become: true
  vars:
    username_to_check: "lava"  # Replace with your username
    ssh_password: "jFtN4oyoQGhZ"  # User password here
  tasks:

    - name: Check if the user exists on the system
      ansible.builtin.command: id {{ username_to_check }}
      register: user_check
      ignore_errors: true

    - name: Display user existence result
      ansible.builtin.debug:
        msg: >
          {% if user_check.rc == 0 %}
            User '{{ username_to_check }}' exists.
          {% else %}
            User '{{ username_to_check }}' does NOT exist.
          {% endif %}

    - name: Try to login using SSH as the user
      ansible.builtin.command: whoami
      become_user: "{{ username_to_check }}"
      register: impersonation_check
      ignore_errors: true
      when: user_check.rc == 0
      vars:
        ansible_ssh_pass: "{{ ssh_password }}"  # Password for SSH login

    - name: Display impersonation result
      ansible.builtin.debug:
        msg: >
          {% if impersonation_check.rc == 0 %}
            Successfully impersonated '{{ username_to_check }}'.
          {% else %}
            Failed to impersonate '{{ username_to_check }}'.
          {% endif %}
      when: user_check.rc == 0
