- name: Check if a user exists and can run a command
  hosts: all
  gather_facts: false
  vars:
    username_to_check: "lava"   # Replace with the username you created earlier

  tasks:

    - name: Check if user exists in /etc/passwd
      ansible.builtin.getent:
        database: passwd
        key: "{{ username_to_check }}"
      register: passwd_entry

    - name: Fail if user does not exist
      ansible.builtin.fail:
        msg: "User '{{ username_to_check }}' does not exist on the system."
      when: passwd_entry is not defined or passwd_entry is not truthy

    - name: Run 'whoami' as the user using sudo
      ansible.builtin.command: sudo -u {{ username_to_check }} whoami
      register: user_whoami
      ignore_errors: true

    - name: Validate 'whoami' output
      ansible.builtin.debug:
        msg: "Successfully ran 'whoami' as user: {{ user_whoami.stdout }}"
      when: user_whoami.rc == 0

    - name: Show error if command failed
      ansible.builtin.fail:
        msg: "Failed to run command as user '{{ username_to_check }}'. Check sudo access or shell setup."
      when: user_whoami.rc != 0
