---
- name: Manage Windows Server Tasks
  hosts: all
  gather_facts: no
  vars:
    remote_log_path: "C:\\logs\\app.log"
    local_log_path: "./fetched_logs/"
    retrieved_log_path: "./scraped_logs.txt"
    start_time: "02/01/2025 10:00"
    end_time: "02/02/2025 12:00"
    process_to_kill: "notepad.exe"  # Change to any process name or PID

  tasks:
    - name: Ensure local log directory exists
      ansible.builtin.file:
        path: "{{ local_log_path }}"
        state: directory

    - name: Fetch log file from remote server
      win_fetch:
        src: "{{ remote_log_path }}"
        dest: "{{ local_log_path }}"
    
    - name: Scrape logs for specific duration
      win_shell: |
        Get-EventLog -LogName Application -After "{{ start_time }}" -Before "{{ end_time }}" | Out-File -FilePath C:\Temp\scraped_logs.txt
      register: log_output

    - name: Fetch the scraped logs from remote server
      win_fetch:
        src: "C:\\Temp\\scraped_logs.txt"
        dest: "{{ retrieved_log_path }}"
    
    - name: Display scraped logs
      debug:
        msg: "{{ log_output.stdout_lines }}"

    - name: Check high CPU usage processes
      win_shell: Get-Process | Sort-Object -Descending CPU | Select-Object -First 10 Name,CPU,Id
      register: cpu_output

    - name: Display high CPU usage processes
      debug:
        msg: "{{ cpu_output.stdout_lines }}"

    - name: Check high memory usage processes
      win_shell: Get-Process | Sort-Object -Descending WS | Select-Object -First 10 Name,WS,Id
      register: mem_output

    - name: Display high memory usage processes
      debug:
        msg: "{{ mem_output.stdout_lines }}"

    - name: Check disk utilization
      win_shell: Get-PSDrive C | Select-Object Used,Free,UsedPercent
      register: disk_usage

    - name: Display disk usage
      debug:
        msg: "{{ disk_usage.stdout_lines }}"

    - name: Terminate a specific process
      win_shell: Stop-Process -Name "{{ process_to_kill }}" -Force
      ignore_errors: yes
