---
- name: Manage Windows Server Tasks
  hosts: 20.102.105.60
  gather_facts: no

  tasks:
    - name: Fetch log file from Windows server
      win_shell: |
        Get-Content {{ log_file_path }} -Tail 10
      register: fetch_logs
      when: server_ip is defined

    - name: Save fetched logs to a local file
      copy:
        content: "{{ fetch_logs.stdout }}"
        dest: "./fetched_logs.txt"
      when: fetch_logs.stdout is defined

    - name: Scrape logs for a specific time range
      win_shell: |
        Get-EventLog -LogName Application -After "{{ start_time }}" -Before "{{ end_time }}" | Select-Object -First 10
      register: scraped_logs
      when: server_ip is defined

    - name: Save scraped logs to a local file
      copy:
        content: "{{ scraped_logs.stdout }}"
        dest: "./scraped_logs.txt"
      when: scraped_logs.stdout is defined

    - name: Check high CPU and memory usage
      win_shell: |
        Get-Process | Sort-Object -Descending CPU | Select-Object -First 10 Name,CPU,Id
        Get-Process | Sort-Object -Descending WS | Select-Object -First 10 Name,WS,Id
      register: process_usage
      when: server_ip is defined

    - name: Save CPU and memory usage details to a local file
      copy:
        content: "{{ process_usage.stdout }}"
        dest: "./process_usage.txt"
      when: process_usage.stdout is defined

    - name: Check disk utilization
      win_shell: |
        Get-PSDrive C | Select-Object Used,Free,UsedPercent
      register: disk_utilization
      when: server_ip is defined

    - name: Save disk utilization details to a local file
      copy:
        content: "{{ disk_utilization.stdout }}"
        dest: "./disk_utilization.txt"
      when: disk_utilization.stdout is defined

    - name: Kill a specific process
      win_shell: |
        Stop-Process -Id {{ process_pid }} -Force
      when: process_pid is defined and server_ip is defined
      register: kill_process_result

    - name: Display process termination result
      debug:
        msg: "Process {{ process_pid }} terminated successfully."
      when: kill_process_result.stdout is defined
